version: '3'

networks:
  swetask-inet:
    driver: bridge

services:

  swetask:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - DB_HOST=database
      - DB_USER=swetask
      - DB_PASS=ksatews
      - CGO_ENABLED=0
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - swetask-inet

  database:
    container_name: database
    image: mariadb:10.5.5
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ksatews
      - MYSQL_DATABASE=swetask
      - MYSQL_USER=swetask
      - MYSQL_PASSWORD=ksatews
    restart: on-failure
    networks:
      - swetask-inet